server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:db}:${RDS_PORT:3306}/${RDS_DB_NAME:academy-db-local}
    username: ${RDS_USERNAME:admin}
    password: ${RDS_PASSWORD:Academy1!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update