POST http://localhost:8080/professors
Content-Type: application/json

{
  "name": "Shivakumar R"
}

###
GET http://localhost:8080/professors
Content-Type: application/json

###
GET http://localhost:8080/professors/1
Content-Type: application/json